### PR TITLE
ADD: ITK based math ops

### PR DESCRIPTION
**Pull request by jeffduda**
ITK filter based implementations for 'antsImage' as input to most ops in the "Math" group.

### CODE REVIEW

**Comment by muschellij2** [comment]
I may have already sent this, but can you add a ` base = exp(1)` argument to `log` similar to the `base::log` function?

**Comment by jeffduda** [comment]
updated the log function as requested.

**Comment by muschellij2** [comment]
So this cannot take in a generic base?

**Comment by muschellij2** [comment]
Nice! +1 for log math!

**Comment by jeffduda** [comment]
ok, now works for any base

**Comment by stnava** [comment]
awesome - will test now

**Comment by stnava** [comment]
i am not sure what timings were before this change but these look good.  

this test times R array operations in comparison to antsImage operations and reaches a speed up of over a factor of 10!

i use `export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=8` in my environment before starting R (multithreading)

```

library(ANTsRCore)
sz <- 666
im1=makeImage( c(sz,sz,sz ) )
arr1 <- as.array(im1)
arr2=arr3=arr1+1
im2=antsImageClone(im1)
im3=antsImageClone(im1)+1
t1=system.time(((arr1 * arr2) / arr3) > 24)[3]
t2=system.time(((im1 * im2) / im3) > 24)[3]
print(paste("Speedup",t1/t2))

```

**Pull request merged**
