### PR TITLE
imageSimilarity and antsrImageToImageMetric

### PR DESCRIPTION
**Pull request by jeffduda**
A wrapper for itk::ImageToImageMetricv4 is provided with support for all valid v4 metrics via the standard Rcpp::wrap and Rcpp::as template specializations. These are made available for use via the user-friendly imageSimilarity().

### CODE REVIEW

**Comment by stnava** [comment]
checks failing - looks like some simple include / fix  - definitely a very valuable ENH

**Comment by muschellij2** [comment]
Looks like we can merge - @stnava agree?

**Comment by stnava** [comment]
Yup

**Comment by stnava** [comment]
fixed in master

**Pull request merged**
